### ISSUE TITLE
Switch to StateMachine model

### ISSUE THREAD

**Issue by SinaKK** [jtanx/picopterx#14]
So for the server, one alternative is to switch to a StateMachine model similar to [this](http://gamedev.stackexchange.com/a/28955).

This would eliminate the messy `if` and `switch` statements an state variables etc...

Needs to be fleshed out but my initial thoughts would be something like this:
```
StateMachine
--
    State currentState
--
  +string getState() // State Details
   +bool changeState(State newState) // attempts to change to new state, false if not allowed
 +update() // state operations are done here
```
```
State
--
 +getState()
 +update()
```
```
StateMachine sm = new StateMachine()
 sm.changeState(new IdleState());
worker thread{
    
    while(1){
        sm.update();
    }
}
```

Hmm, needs some work. Maybe just a State class and an atomic variable to store the current one...  I'll put more thought into it later, feel free to suggest/criticise.

**Comment by jtanx** [comment]
I'll consider this just about done... The [flight controller](https://github.com/jtanx/picopterx/blob/master/code/src/base/flightcontroller.cpp) handles state control and the currently run task has a method handle to change the state as it runs.
