### ISSUE TITLE
Tilt servo is dead

### ISSUE THREAD

**Issue by jtanx** [jtanx/picopterx#33]
Replace it!!!

**Comment by BrettRD** [comment]
Tilt servo should be size 81,  replaced by a spare size 80 which has had its brackets filed off.
The mounting is all pretty temporary.

**Comment by BrettRD** [comment]
We should be thinking about a three-axis gimbal now.
Either make one with servos, or buy something like the tarot.

**Comment by BrettRD** [comment]
Servo Nodding: known bug. 
Poor connection at the user-switch chopping up the servo pulses, combined with slow mechanical response.  Fixed for now.

**Comment by BrettRD** [comment]
The pixhawk seems to be handling the gimbal ok.
The size 80 servo has been on for long enough that I've just glued it down.

**Comment by jtanx** [comment]
Haha nice!
