### ISSUE TITLE
MAVLINK

### ISSUE THREAD

**Issue by jtanx** [jtanx/picopterx#40]
We need it

**Comment by BrettRD** [comment]
Link Dump:

Basic tute to building the C includes
  http://qgroundcontrol.org/mavlink/create_new_mavlink_message
C bindings exist
  https://github.com/mavlink/mavlink
C uart example
  https://github.com/mavlink/c_uart_interface_example
Python CLI interface:
  http://tridge.github.io/MAVProxy/
ROS driver exitss
  https://github.com/mavlink/mavros
Basic API (using mavproxy maybe)
  http://dev.ardupilot.com/wiki/droneapi-tutorial/
Probably useless
  https://github.com/hybridgroup/gobot/blob/master/examples/mavlink.go

**Comment by jtanx** [comment]
We have a Pixhawk (but no GPS) as of 14/05/2015

**Comment by jtanx** [comment]
Probably: MAV_CMD_NAV_GUIDED_ENABLE
