### ISSUE TITLE
Object tracker: Kp is still linked between the x and y PID controllers

### ISSUE THREAD

**Issue by jtanx** [jtanx/picopterx#41]
They should have separate Kp values... I don't know why this wasn't separated when they were made to have separate setpoints/limits...

**Comment by BrettRD** [comment]
The changes to the input linearisation need pitch, roll and yaw filters to do all of the magic now, and it wouldn't hurt to have a throttle loop available for later.

**Comment by jtanx** [comment]
Well, they're not linked anymore.
